### ISSUE TITLE
Add users name above message

### ISSUE THREAD

**Issue by brad555** [fayeed/dash_chat#113] opened 2020-07-18 20:17 UTC
similar to how you can add an avatar URL, it would be nice If you could add the name of the user in the message container... makes it less confusing for group chats

**Comment by fayeed** [comment] 2020-07-19 02:35
As I mentioned I am planning a new version for this package and it will have a lot of improvement build in over this version, for now, though you should be able to implement this yourself using `messageBuilder`.

**Comment by SebastienBtr** [comment] 2020-07-19 09:46
Duplicate of #101

**Closed** 2020-08-02 20:55 UTC
Labels: duplicate
