### ISSUE TITLE
IOS widgets margin in bottom

### ISSUE THREAD

**Issue by poovarasanvasudevan** [fayeed/dash_chat#1] opened 2019-08-04 09:14 UTC
i am using this for ios cuppertino widgets 
all working fine but there is little margin at the bottom

![image](https://user-images.githubusercontent.com/8036283/62421852-86b91100-b65d-11e9-9da1-9bb7b2d3682b.png)

Code : 
```
class UserMessagePageState extends State<UserMessagePage> {
  final ChatUser user = ChatUser(
    name: "Poovarasan",
    uid: "123456789",
    avatar: "https://avatars1.githubusercontent.com/u/8036283?s=460&v=4",
  );
  final ChatUser otherUser = ChatUser(
    name: "Poovarasanv",
    uid: "123456780",
    avatar: "https://avatars1.githubusercontent.com/u/8036283?s=460&v=4",
  );

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: CupertinoNavigationBar(
        middle: Text("Message"),
      ),

      body: Container(
        decoration: BoxDecoration(
          color: Colors.green,
        ),
        child: SafeArea(
          child: Material(
            child: Padding(
              padding: const EdgeInsets.only(bottom: 0.0),
              child: DashChat(
                onSend: (ChatMessage message) {},
                messages: [
                  ChatMessage(text: "Hello", user: user, id: "hello"),
                  
                ],
                user: user,
                dateFormat: DateFormat('yyyy-MMM-dd'),
                timeFormat: DateFormat('HH:mm'),
                alwaysShowSend: false,
                messageContainerPadding: EdgeInsets.zero,
                inputContainerStyle: BoxDecoration(
                  border: Border.all(
                      width: 1.0, color: CupertinoColors.lightBackgroundGray),
                  color: Colors.white,
                ),
                shouldShowLoadEarlier: true,
                showTraillingBeforeSend: true,
                trailing: <Widget>[
                  IconButton(
                    icon: Icon(Feather.camera),
                    onPressed: () {
                      print("object");
                    },
                  )
                ],
                sendButtonBuilder: (Function click) {
                  return IconButton(
                    icon: Icon(Feather.send),
                    onPressed: click,
                  );
                },
                leading: <Widget>[
                  IconButton(
                    icon: Icon(Feather.paperclip),
                    onPressed: () {
                      print("object");
                    },
                  )
                ],
                inputDecoration: InputDecoration.collapsed(
                  hintText: "Add message here...",
                ),


//              inputFooterBuilder: () {
//                return Text("Hello");
//              }
              ),
            ),
          ),
        ),
      ),
      //resizeToAvoidBottomPadding: true,
    );
  }
}

```

**Comment by fayeed** [comment] 2019-08-05 02:07
You are actually adding a Text widget below the input tool bar by overriding the `inputFooterBuilder` try removing it or maybe give some style to it.

**Comment by fayeed** [comment] 2019-08-05 08:05
@poovarasanvasudevan The reason you are getting the problem is I have hardcoded a height value if no height is supplied, which is based after android i.e `screen height - 80.0` which results in a weird space below the input toolbar because of the `CupertinoNavigationBar` height is less, I forgot to change the code so I will update it later, in the meantime you could do something like this.

Define your app bar above `build` method like so, we will use it get the app bars height:
```dart
  var appbar = CupertinoNavigationBar(
    middle: Text("Message"),
  );
````
And in DashChat widget add this:
```dart
DashChat(
  height: MediaQuery.of(context).size.height -
            (appbar.preferredSize.height +
                MediaQuery.of(context).viewPadding.top),
);
```

**Comment by fayeed** [comment] 2019-08-08 04:29
@poovarasanvasudevan I going to close this issue now if you have some other problem feel free to create a new issue.

**Closed by fayeed** 2019-08-08 04:29 UTC
